include_recipe "base::user"
include_recipe "base::files"
include_recipe "base::gcc"
include_recipe "base::git"
include_recipe "base::iptables"
include_recipe "base::rpm-build"
include_recipe "base::yum"
